/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthAccount {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AuthApikey {
  configId: string;
  createdAt: Timestamp;
  enabled: boolean | null;
  expiresAt: Timestamp | null;
  id: string;
  key: string;
  lastRefillAt: Timestamp | null;
  lastRequest: Timestamp | null;
  metadata: string | null;
  name: string | null;
  permissions: string | null;
  prefix: string | null;
  rateLimitEnabled: boolean | null;
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  referenceId: string;
  refillAmount: number | null;
  refillInterval: number | null;
  remaining: number | null;
  requestCount: number | null;
  start: string | null;
  updatedAt: Timestamp;
}

export interface AuthSession {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface AuthUser {
  createdAt: Generated<Timestamp>;
  displayUsername: string | null;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface AuthVerification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface CoverfetchBooks {
  createdAt: Generated<Timestamp>;
  hardcoverId: string;
  id: Generated<number>;
  title: string;
}

export interface CoverfetchMigrationsDbMigrations {
  name: string;
  timestamp: string;
}

export interface CoverfetchReadingStrategies {
  bookId: number;
  content: Json;
  familiarity: string;
  generatedAt: Timestamp;
  id: Generated<number>;
}

export interface DB {
  "auth.account": AuthAccount;
  "auth.apikey": AuthApikey;
  "auth.session": AuthSession;
  "auth.user": AuthUser;
  "auth.verification": AuthVerification;
  "coverfetch.books": CoverfetchBooks;
  "coverfetch.readingStrategies": CoverfetchReadingStrategies;
  "coverfetchMigrations.dbMigrations": CoverfetchMigrationsDbMigrations;
}
